import { z } from "zod";
import type { SystemEventType } from "./types.ts";

/**
 * Payloads cerrados por tipo de evento.
 *
 * El Record obliga a cubrir TODOS los SystemEventType: si anades uno
 * al enum y no aqui, TypeScript no compila. Eso es intencional.
 *
 * La validacion vive en el emisor (EventBus.emit), nunca en el consumidor.
 */

const base = {
  taskId: z.string().max(200).optional(),
  actionId: z.string().max(200).optional(),
  monitorId: z.string().max(200).optional(),
  sopId: z.string().max(200).optional(),
  stepId: z.string().max(200).optional(),
  projectId: z.string().max(200).optional(),
  clientId: z.string().max(200).optional(),
  roleId: z.string().max(200).optional(),
};

export const payloadSchemas: Record<SystemEventType, z.ZodTypeAny> = {
  "task.created": z.object({ ...base, title: z.string().max(200), kind: z.string().max(40) }),
  "task.status_changed": z.object({ ...base, from: z.string().max(40), to: z.string().max(40) }),
  "task.completed": z.object({ ...base, title: z.string().max(200), result: z.string().max(2000).optional() }),
  "task.failed": z.object({ ...base, title: z.string().max(200), error: z.string().max(2000).optional() }),
  "task.waiting_input": z.object({ ...base, title: z.string().max(200), question: z.string().max(2000).optional() }),
  "task.waiting_approval": z.object({ ...base, title: z.string().max(200) }),
  "task.controlled": z.object({ ...base, action: z.enum(["pause","resume","cancel","retry"]) }),
  "sop.step_started": z.object({ ...base, index: z.number().int().nonnegative(), title: z.string().max(200) }),
  "sop.step_completed": z.object({ ...base, index: z.number().int().nonnegative(), title: z.string().max(200) }),
  "sop.step_skipped": z.object({ ...base, index: z.number().int().nonnegative(), title: z.string().max(200), reason: z.string().max(500).optional() }),
  "sop.failed": z.object({ ...base, error: z.string().max(2000).optional() }),
  "action.proposed": z.object({ ...base, title: z.string().max(300), kind: z.string().max(60) }),
  "action.approved": z.object({ ...base, title: z.string().max(300) }),
  "action.denied": z.object({ ...base, title: z.string().max(300) }),
  "action.executed": z.object({ ...base, title: z.string().max(300), result: z.string().max(2000).optional() }),
  "action.failed": z.object({ ...base, title: z.string().max(300), error: z.string().max(2000).optional() }),
  "action.outcome_unknown": z.object({ ...base, title: z.string().max(300), error: z.string().max(2000).optional() }),
  "monitor.check": z.object({ ...base, url: z.string().max(2000), matched: z.boolean() }),
  "monitor.changed": z.object({ ...base, url: z.string().max(2000), excerpt: z.string().max(1000) }),
  "monitor.failed": z.object({ ...base, url: z.string().max(2000), error: z.string().max(2000) }),
  "system.startup": z.object({ mode: z.enum(["sample", "live"]) }),
  "system.error": z.object({ message: z.string().max(2000), phase: z.string().max(100).optional() }),
  "system.maintenance": z.object({ tasks: z.number().int().nonnegative(), monitors: z.number().int().nonnegative() }),
  "system.google_disconnected": z.object({ owner: z.string().max(200) }),
  "auth.login": z.object({ userId: z.string().max(200) }),
  "auth.login_failed": z.object({ email: z.string().max(300) }),
  // A2_EVENTS_V1 - undo diferido y cancelacion de acciones.
  "action.deferred": z.object({
    ...base,
    actionId: z.string().max(200),
    signers: z.array(z.string().max(200)).max(10),
    needed: z.number().int().min(1).max(10),
    executeAt: z.number().nullable(),
  }),
  "action.cancelled": z.object({
    ...base,
    actionId: z.string().max(200),
    by: z.string().max(200),
  }),
  // D2_VIEW_RESOLVED_V1 - spec servido por el agente.
  "view.resolved": z.object({
    ...base,
    kind: z.enum(["dashboard", "queue"]),
    title: z.string().max(300),
    spec: z.record(z.string(), z.unknown()),
  }),
  // SCHEMAS_V2 — business graph, policy, state machine, agent runtime, context.
  "entity.created": z.object({
    ...base,
    entityId: z.string().max(200),
    entityType: z.string().max(100),
    version: z.number().int().positive(),
  }),
  "entity.updated": z.object({
    ...base,
    entityId: z.string().max(200),
    entityType: z.string().max(100),
    version: z.number().int().positive(),
    changedFields: z.array(z.string().max(100)).max(100),
  }),
  "entity.deleted": z.object({
    ...base,
    entityId: z.string().max(200),
    entityType: z.string().max(100),
  }),
  "relation.created": z.object({
    ...base,
    relationId: z.string().max(200),
    fromEntityId: z.string().max(200),
    toEntityId: z.string().max(200),
    relationType: z.string().max(100),
  }),
  "relation.deleted": z.object({
    ...base,
    relationId: z.string().max(200),
  }),
  "policy.evaluated": z.object({
    ...base,
    policyId: z.string().max(200),
    decision: z.enum(["allow", "deny"]),
    action: z.string().max(200),
  }),
  "policy.denied": z.object({
    ...base,
    policyId: z.string().max(200),
    action: z.string().max(200),
    reason: z.string().max(1000),
  }),
  "state.changed": z.object({
    ...base,
    entityId: z.string().max(200),
    stateMachine: z.string().max(100),
    from: z.string().max(100).optional(),
    to: z.string().max(100),
  }),
  "state.transition_denied": z.object({
    ...base,
    entityId: z.string().max(200),
    stateMachine: z.string().max(100),
    from: z.string().max(100),
    attempted: z.string().max(100),
    reason: z.string().max(1000),
  }),
  "agent.runtime_spawned": z.object({
    ...base,
    runtimeId: z.string().max(200),
    roleId: z.string().max(200),
    taskId: z.string().max(200),
  }),
  "agent.runtime_completed": z.object({
    ...base,
    runtimeId: z.string().max(200),
    roleId: z.string().max(200),
    taskId: z.string().max(200),
    durationMs: z.number().int().nonnegative(),
  }),
  "agent.runtime_failed": z.object({
    ...base,
    runtimeId: z.string().max(200),
    roleId: z.string().max(200),
    taskId: z.string().max(200),
    error: z.string().max(2000),
  }),
  "context.assembled": z.object({
    ...base,
    roleId: z.string().max(200).optional(),
    runtimeId: z.string().max(200).optional(),
    entityCount: z.number().int().nonnegative(),
    relationCount: z.number().int().nonnegative(),
    knowledgeCount: z.number().int().nonnegative(),
    policyCount: z.number().int().nonnegative(),
  }),

  // VERIFICATION_EVENT_V1
  "verification.executed": z.object({
    ...base,
    goalId: z.string().max(200).optional(),
    verified: z.boolean(),
    method: z.enum(["deterministic", "llm", "hybrid", "manual"]),
    confidence: z.number().min(0).max(1),
  }),
  "verification.disagreement": z.object({
    ...base,
    goalId: z.string().max(200).optional(),
    deterministic: z.boolean(),
    llm: z.boolean(),
  // WORKSPACE_EVENT_SCHEMAS_V1 - sobre comun de eventos de workspace.
  // Los payloads especificos se validan en el adapter del bus por workspace.
  // Mientras cada workspace no declare su schema, se valida el sobre minimo comun.
  "email.received": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "email.sent": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "email.thread.linked": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "email.label.applied": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "whatsapp.message.received": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "whatsapp.message.sent": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "whatsapp.identity.linked": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "lead.created": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "opportunity.created": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "opportunity.stage.changed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "sales.activity.logged": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "invoice.drafted": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "invoice.issued": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "invoice.paid": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "invoice.voided": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "expense.recorded": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "document.uploaded": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "document.classified": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "document.linked": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "document.archived": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "calendar.event.created": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "calendar.event.rescheduled": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "calendar.event.cancelled": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "workitem.created": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "workitem.assigned": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "workitem.completed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "workitem.blocked": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "assistant.run.started": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "assistant.run.completed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "assistant.tool.invoked": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "dataset.record.created": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "dataset.record.updated": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "objective.created": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "keyresult.updated": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "objective.closed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "bank.transaction.imported": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "bank.transaction.reconciled": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "bank.discrepancy.detected": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "purchase.requested": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "purchase.order.approved": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "purchase.order.received": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "resource.allocated": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "time.logged": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "budget.adjusted": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "ticket.created": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "ticket.assigned": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "ticket.resolved": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "ticket.escalated": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "envelope.prepared": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "envelope.sent": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "envelope.signed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "envelope.completed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "workflow.executed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "workflow.failed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "workflow.completed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "sop.started": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "sop.aborted": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "employee.created": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "leave.approved": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "leave.rejected": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "attendance.recorded": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "position.opened": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "onboarding.started": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "onboarding.completed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "employment.closed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "expense.submitted": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "expense.approved": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "expense.rejected": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "expense.receipt.attached": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "payment.succeeded": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "payment.failed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "refund.issued": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "dispute.opened": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "brief.created": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "design.generated": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "asset.exported": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "asset.published": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "post.composed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "post.scheduled": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "post.published": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "post.metrics.collected": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "order.created": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "order.fulfilled": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "order.returned": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "inventory.synced": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "conversation.opened": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "conversation.routed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "conversation.closed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "stock.received": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "stock.issued": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "stock.transferred": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "stock.adjusted": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "stock.low": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "asset.registered": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "maintenance.opened": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "maintenance.completed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "inspection.recorded": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "production.planned": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "production.started": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "production.output.recorded": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "production.closed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "risk.registered": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "control.assigned": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "evidence.attached": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "review.scheduled": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "principal.created": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "role.assigned": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "access.revoked": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "policy.updated": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "portal.invited": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "request.submitted": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "case.updated": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "document.shared": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "page.created": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "page.updated": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "page.archived": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "run.recorded": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "span.recorded": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "evaluation.submitted": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "board.created": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "card.created": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "card.moved": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "card.archived": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
  "verification.executed": z.object({
    tenantId: z.string().max(100).optional(),
    workspaceId: z.string().max(100).optional(),
    entityId: z.string().max(200).optional(),
    correlationId: z.string().max(200).optional(),
    occurredAt: z.string().optional(),
  }).passthrough(),
    }),};