// WS_CAPABILITIES_FULL_V1 - declaracion completa de capacidades (9 campos).
// Los 5 campos ampliados (description, sideEffects, requiresApproval, inputs, outputs)
// los exige capabilityDeclarationSchema. Se rellenan aqui para no romper el contrato.
import type { CapabilityDeclaration } from "../../../src/contracts/index.ts";

export const CAPABILITIES: readonly CapabilityDeclaration[] = [
  {
    id: "email.read",
    title: "email.read",
    description: "email.read",
    kind: "query",
    risk: "low",
    sideEffects: false,
    requiresApproval: false,
    inputs: {},
    outputs: {},
  },
  {
    id: "email.search",
    title: "email.search",
    description: "email.search",
    kind: "query",
    risk: "low",
    sideEffects: false,
    requiresApproval: false,
    inputs: {},
    outputs: {},
  },
  {
    id: "email.send",
    title: "email.send",
    description: "email.send",
    kind: "action",
    risk: "low",
    sideEffects: true,
    requiresApproval: true,
    inputs: {},
    outputs: {},
  },
  {
    id: "email.compose",
    title: "email.compose",
    description: "email.compose",
    kind: "action",
    risk: "low",
    sideEffects: true,
    requiresApproval: false,
    inputs: {},
    outputs: {},
  },
  {
    id: "email.label",
    title: "email.label",
    description: "email.label",
    kind: "action",
    risk: "low",
    sideEffects: true,
    requiresApproval: false,
    inputs: {},
    outputs: {},
  },
  {
    id: "email.archive",
    title: "email.archive",
    description: "email.archive",
    kind: "action",
    risk: "low",
    sideEffects: true,
    requiresApproval: true,
    inputs: {},
    outputs: {},
  },
  {
    id: "email.attach",
    title: "email.attach",
    description: "email.attach",
    kind: "action",
    risk: "low",
    sideEffects: true,
    requiresApproval: false,
    inputs: {},
    outputs: {},
  },
  {
    id: "email.link_thread",
    title: "email.link_thread",
    description: "email.link_thread",
    kind: "action",
    risk: "low",
    sideEffects: true,
    requiresApproval: false,
    inputs: {},
    outputs: {},
  },
];
